# Generated by Django 4.2.7 on 2025-07-15 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_steps', models.TextField()),
                ('products_needed', models.TextField(blank=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('timeframe', models.CharField(blank=True, max_length=100)),
                ('urgency_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Treatment Recommendation',
                'verbose_name_plural': 'Treatment Recommendations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='diagnosisresult',
            name='detected_diseases',
        ),
        migrations.RemoveField(
            model_name='diagnosisresult',
            name='diagnosis_request',
        ),
        migrations.RemoveField(
            model_name='diseasedetection',
            name='diagnosis_result',
        ),
        migrations.RemoveField(
            model_name='diseasedetection',
            name='disease',
        ),
        migrations.AlterModelOptions(
            name='crop',
            options={'ordering': ['name'], 'verbose_name': 'Crop', 'verbose_name_plural': 'Crops'},
        ),
        migrations.AlterModelOptions(
            name='diagnosisrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Diagnosis Request', 'verbose_name_plural': 'Diagnosis Requests'},
        ),
        migrations.AlterModelOptions(
            name='disease',
            options={'ordering': ['name'], 'verbose_name': 'Disease', 'verbose_name_plural': 'Diseases'},
        ),
        migrations.AlterModelOptions(
            name='feedbackrating',
            options={'ordering': ['-created_at'], 'verbose_name': 'Feedback Rating', 'verbose_name_plural': 'Feedback Ratings'},
        ),
        migrations.RemoveField(
            model_name='crop',
            name='category',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='growing_season',
        ),
        migrations.RemoveField(
            model_name='diagnosisrequest',
            name='description',
        ),
        migrations.RemoveField(
            model_name='diagnosisrequest',
            name='gps_coordinates',
        ),
        migrations.RemoveField(
            model_name='diagnosisrequest',
            name='processing_time',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='causes',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='crops',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='prevention_methods',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='severity',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='treatment_methods',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='feedbackrating',
            name='accuracy_rating',
        ),
        migrations.RemoveField(
            model_name='feedbackrating',
            name='diagnosis_result',
        ),
        migrations.RemoveField(
            model_name='feedbackrating',
            name='usefulness_rating',
        ),
        migrations.RemoveField(
            model_name='feedbackrating',
            name='user',
        ),
        migrations.RemoveField(
            model_name='feedbackrating',
            name='would_recommend',
        ),
        migrations.AddField(
            model_name='diagnosisrequest',
            name='farmer_notes',
            field=models.TextField(blank=True, help_text='Additional notes from the farmer'),
        ),
        migrations.AddField(
            model_name='diagnosisrequest',
            name='is_healthy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diagnosisrequest',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='diagnosisrequest',
            name='predicted_disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnosis.disease'),
        ),
        migrations.AddField(
            model_name='diagnosisrequest',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisrequest',
            name='severity',
            field=models.CharField(blank=True, choices=[('NONE', 'None'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='affected_crops',
            field=models.ManyToManyField(blank=True, related_name='diseases', to='diagnosis.crop'),
        ),
        migrations.AddField(
            model_name='disease',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AddField(
            model_name='disease',
            name='prevention',
            field=models.TextField(default='No prevention information available'),
        ),
        migrations.AddField(
            model_name='disease',
            name='severity_level',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=20),
        ),
        migrations.AddField(
            model_name='disease',
            name='treatment',
            field=models.TextField(default='No treatment information available'),
        ),
        migrations.AddField(
            model_name='feedbackrating',
            name='actual_disease',
            field=models.ForeignKey(blank=True, help_text='What was the actual disease if diagnosis was wrong?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnosis.disease'),
        ),
        migrations.AddField(
            model_name='feedbackrating',
            name='diagnosis_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='diagnosis.diagnosisrequest'),
        ),
        migrations.AddField(
            model_name='feedbackrating',
            name='is_diagnosis_accurate',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedbackrating',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=3),
        ),
        migrations.AlterField(
            model_name='crop',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosisrequest',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diagnosis.crop'),
        ),
        migrations.AlterField(
            model_name='diagnosisrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='diagnosisrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='diagnosisrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='diagnosisrequest',
            index=models.Index(fields=['user', 'status'], name='diagnosis_d_user_id_d41ead_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosisrequest',
            index=models.Index(fields=['created_at'], name='diagnosis_d_created_5e1bdb_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosisrequest',
            index=models.Index(fields=['status'], name='diagnosis_d_status_99d74b_idx'),
        ),
    ]
