# Generated by Django 4.2.7 on 2025-07-15 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_savedrecommendation_remove_treatment_category_and_more'),
        ('diagnosis', '0002_treatmentrecommendation_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiagnosisResult',
        ),
        migrations.DeleteModel(
            name='DiseaseDetection',
        ),
        migrations.AddField(
            model_name='treatmentrecommendation',
            name='diagnosis_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='diagnosis.diagnosisrequest'),
        ),
        migrations.AddField(
            model_name='treatmentrecommendation',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnosis.disease'),
        ),
    ]
