# Generated by Django 4.2.7 on 2025-07-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0003_delete_diagnosisresult_delete_diseasedetection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosisrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
