# Generated by Django 4.2.7 on 2025-07-15 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0003_delete_diagnosisresult_delete_diseasedetection_and_more'),
        ('diagnosis', '0004_convert_uuid_to_bigint'),
    ]

    operations = [
    ]
