# Generated by Django 4.2.7 on 2025-07-15 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0005_merge_20250715_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosisrequest',
            name='severity',
            field=models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='affected_crops',
            field=models.ManyToManyField(related_name='diseases', to='diagnosis.crop'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='disease',
            name='image',
            field=models.ImageField(blank=True, upload_to='disease_images/'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='disease',
            name='prevention',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='disease',
            name='severity_level',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=20),
        ),
        migrations.AlterField(
            model_name='disease',
            name='treatment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='feedbackrating',
            name='diagnosis_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='diagnosis.diagnosisrequest'),
        ),
        migrations.AlterField(
            model_name='feedbackrating',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')]),
        ),
    ]
