# Generated by Django 4.2.7 on 2025-07-15 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0002_treatmentrecommendation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='category',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='diseases',
        ),
        migrations.RemoveField(
            model_name='treatmentrecommendation',
            name='recommendation',
        ),
        migrations.RemoveField(
            model_name='treatmentrecommendation',
            name='treatment',
        ),
        migrations.AlterUniqueTogether(
            name='treatmenttracking',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='treatmenttracking',
            name='recommendation',
        ),
        migrations.RemoveField(
            model_name='treatmenttracking',
            name='treatment',
        ),
        migrations.RemoveField(
            model_name='treatmenttracking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='custom_recommendations',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='diagnosis_result',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='estimated_cost',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='follow_up_date',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='follow_up_required',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='priority_level',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='timeline',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='treatments',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='description',
            field=models.TextField(default='No description provided'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendation',
            name='diagnosis',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='diagnosis.diagnosisrequest'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendation',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='steps',
            field=models.TextField(default=None, help_text='Step-by-step treatment plan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendation',
            name='title',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PreventiveMeasure',
        ),
        migrations.DeleteModel(
            name='Treatment',
        ),
        migrations.DeleteModel(
            name='TreatmentCategory',
        ),
        migrations.DeleteModel(
            name='TreatmentRecommendation',
        ),
        migrations.DeleteModel(
            name='TreatmentTracking',
        ),
        migrations.AddField(
            model_name='savedrecommendation',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.recommendation'),
        ),
        migrations.AddField(
            model_name='savedrecommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='savedrecommendation',
            unique_together={('user', 'recommendation')},
        ),
    ]
