# Generated by Django 4.2.7 on 2025-07-15 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommendations', '0002_savedrecommendation_remove_treatment_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
